import type { NextPage } from 'next'
import React, { useEffect } from "react"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { motion, useAnimation, AnimatePresence } from 'framer-motion'
import Test1 from '../components/index/Test1'

const Home: NextPage = () => {
  const mainControls = useAnimation()

  const startupSquence = async () => {
    await mainControls.start({
      display: "block"
    })
    await mainControls.start({
      background: "rgb(29, 29, 29)",
      transition: {
        delay: 1,
        duration: 1.3
      }
    })

    

    await mainControls.start({
      opacity: 0,
      transition: {
        duration: 1.3
      }
    })
    return await mainControls.start({
      display: "none"
    })
  }

  useEffect(() => { startupSquence() })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div animate={mainControls} className={styles.opening}>
        
      </motion.div>

      <main className={styles.main}>
        <Test1 />
      </main>

    </div>
  )
}

export default Home
