import type { NextPage } from 'next'
import { useEffect } from "react"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { motion, useAnimation } from 'framer-motion'
import Test1 from '../components/index/Test1'

const Home: NextPage = () => {
  const mainControls = useAnimation()

  const startupSquence = async () => {
    return await mainControls.start({
      background: "rgb(29, 29, 29)",
      transition: {
        delay: 1,
        duration: 2
      }
    })
  }

  useEffect(() => { startupSquence() })

  return (
    <motion.div className={styles.container} animate={mainControls}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Test1 />
      </main>

    </motion.div>
  )
}

export default Home
